import random
from typing import Final

BINGO_ITEMS: Final[list[str]] = [
    "German tourist on snowboard",
    "Chairlift speed wanker (overtaking on lifts)",
    "Someone falling on a green run",
    "Apres-ski dance floor chaos",
    "Where's the party? Dutchie",
    "Hot tub selfie",
    "Piste bash survivor",
    "Lift line rage quit",
    "Apres-ski Jagerbomb",
    "Someone in jeans on the mountain",
    "Austrian guy with fanny pack",
    "First wipeout of the day",
    "Fondue grease monster",
    "It's actually my first time skiing",
    "Apres-ski karaoke disaster",
    "Dutchie wearing clogs to the bar",
    "Someone taking a 'skiing' photo while standing",
    "Lost phone in snow (found 20min later)",
    "Sunglasses lost to the mountain gods",
    "The I'll just have one beer liar",
    "Someone who's been skiing for years but falls on everything",
    "Group photo that takes 10 minutes to arrange",
    "Is this the blue or black run?",
    "Ski patrol looking for someone",
    "Chairlift that stops for 5 minutes",
    "Someone dropping 50 euro on hot chocolate",
    "Let's do one more run at 3pm",
    "The friend who films everything but never shares",
    "Someone skiing in a onesie",
    "Austrian instructor with best curves energy",
    "My goggles are fogging up",
    "Lift ticket in the wrong pocket",
    "Someone who forgot their gloves",
    "Wait, which way is the cabin?",
    "Dutchie ordering in broken German",
    "The I'm not cold liar (shivering 10min later)",
    "Someone eating fondue for the 3rd day in a row",
    "Best snow of my life (it's March)",
    "Lost ski pole",
    "Someone yodeling (ironically or not)",
    "The last lift that isn't actually last",
    "My boots are too tight",
    "Someone skiing with headphones in",
    "The mandatory apricot brandy shot",
    "Let's meet at the bottom (different bottoms)",
    "Someone sliding down on their stomach",
    "Group trying to unbuckle skis for 5 minutes",
    "I definitely didn't book the early morning",
    "The friend who falls asleep after lunch",
    "Apres-ski dance move fail",
    "Is the hot tub warm enough?",
    "Someone wearing ski socks with sandals",
    "Let's take the shortcut disaster",
    "My season pass is in the other jacket",
    "Apres-ski I love this song followed by silence",
    "Someone who brought their own hot sauce",
    "The I'll drive tomorrow person (who can't)",
    "Gondola selfie that everyone ignores",
    "I can't feel my toes",
    "Someone wearing a helmet but no sunscreen",
    "Let's go off-piste (lasts 30 seconds)",
    "The I'm buying the first round forever person",
    "My ski is making a weird noise",
    "Apres-ski booth that doesn't exist",
    "Someone arguing with the bartender in German",
    "This is cheaper than Dutch prices",
    "The friend who takes 45 minutes to get ready",
    "I definitely didn't get sunburned yesterday",
    "Someone who brought a onesie for every day",
    "Let's do a shot, it's 11am",
    "Dutchie complaining about the lack of proper bread",
    "The I'm perfectly fine after a crash",
    "Is there WiFi here? (it's 2025, always yes)",
    "Someone who counted all 47 runs on the map",
    "The snow is perfect today (it's raining)",
    "Apres-ski we should do this every year promise",
    "Someone who forgot their ski pass lanyard",
    "My goggles are on backwards",
    "The friend who found the one empty bar",
    "Dutchie explaining why Dutch beer is superior",
    "I'm not tired, it's only 2am",
    "Someone who packed 8 pairs of thermal underwear",
    "We should have done more runs this morning",
    "The one last drink that becomes 5",
    "Someone who googled how to ski before the trip",
    "The Austrians are so friendly (they're just polite)",
    "The friend who fell asleep in the hot tub",
    "Dutchie wearing orange head-to-toe",
    "I didn't mean to fall in love with the instructor",
    "Someone who thinks apricot is a personality trait",
    "The group trying to find the cabin in whiteout conditions",
    "This is better than Val d'Isere (it isn't)",
    "Someone's dad joke about piste",
    "The mandatory apricot shot",
    "Dutchie saying 'lekker' 10 times a day",
    "Someone who only skis the blue runs",
    "Austrian 'Servus' that sounds like 'surfs up'",
    "The I'm scared of heights chairlift freakout",
    "Someone's phone dying from cold",
    "Group debating lunch for 45 minutes",
    "The friend who never has euros",
    "Someone taking a selfie with a cow",
    "Dutchie explaining the郁金香 of skiing",
    "The one more apres-ski that kills the next day",
    "Someone who packed professional ski gear but has never used it",
    "Austrian man with feathered hat giving unsolicited advice",
    "The I-swear-I'm-a-good-skier-but-falls-every-30-seconds person",
    "Someone wearing crocs on the mountain",
    "Dutchie with 47 scarves",
    "The 'no I'm not cold' person shivering in a t-shirt",
]


def get_random_bingo() -> str:
    item = random.choice(BINGO_ITEMS)
    return f"🎿 *BINGO CHALLENGE* 🎿\n\nFind and photograph:\n\n*{item}*\n\nFirst photo proof wins a FREE BEER! 🍺\n\nReply with your photo!"


def get_bingo_item_count() -> int:
    return len(BINGO_ITEMS)
